import React from 'react';
import { useAppStore } from '../store';
import { Icons } from '../icons';
import { COLOR_PUSHOUT } from '../types';
import s from './CaseReportTab.module.css';

export const CaseReportTab: React.FC = () => {
  const { runResult } = useAppStore();
  const html = runResult?.case_report_html;

  const handleCopy = async () => {
    if (!html) return;
    const text = new DOMParser().parseFromString(html, 'text/html').body.innerText;
    await navigator.clipboard.writeText(text);
  };

  return (
    <div className={s.root}>
      <div className={s.toolbar}>
        <span className={s.vlmTag}><Icons.sparkles size={10} /> generated by Claude (Anthropic)</span>
        <div style={{ flex: 1 }} />
        <button className={s.btn} onClick={handleCopy} disabled={!html}><Icons.copy size={11} /> Copy</button>
      </div>

      {html ? (
        <div className={s.docWrap}>
          <div className={s.doc} dangerouslySetInnerHTML={{ __html: html }} />
        </div>
      ) : (
        <div className={s.empty}>
          <Icons.sparkles size={28} style={{ color: 'var(--text-3)', marginBottom: 10 }} />
          <div style={{ fontSize: 13, color: 'var(--text-2)', fontWeight: 500 }}>Case report not generated yet</div>
          <div style={{ fontSize: 11.5, color: 'var(--text-3)', marginTop: 4 }}>
            Enable VLM backend in the left panel and run analysis
          </div>
        </div>
      )}
    </div>
  );
};
